      - name: Deploy to Cloudflare Workers with Wrangler
        uses: cloudflare/wrangler-action@v3.1.0
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          accountId: ${{ secrets.CF_ACCOUNT_ID }}
          environment: keyboxerproxy1
          workingDirectory: .
          command: |
            wrangler publish --env keyboxerproxy1
            wrangler publish --env keyboxerproxy2
